# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json
name: customer-chatbot-solution-accelerator
metadata:
  template: customer-chatbot-solution-accelerator@1.0

requiredVersions:
  azd: ">= 1.18.0 != 1.23.9"

hooks:
  preprovision:
    windows:
      shell: pwsh
      run: ./infra_basic/scripts/preflight_scenario.ps1
      continueOnError: false
      interactive: false
    posix:
      shell: pwsh
      run: ./infra_basic/scripts/preflight_scenario.ps1
      continueOnError: false
      interactive: false
  postprovision:
    windows:
      shell: pwsh
      run: ./infra_basic/scripts/postprovision_all.ps1
      continueOnError: false
      interactive: false
    posix:
      shell: sh
      run: chmod +x ./infra_basic/scripts/postprovision_all.sh && ./infra_basic/scripts/postprovision_all.sh
      continueOnError: false
      interactive: false

infra:
  path: infra_basic

services:
  chat-backend:
    project: ./chat-app/backend
    host: appservice
    language: python
    docker:
      path: Dockerfile
      context: .
      image: ccsa-chat-backend

  chat-frontend:
    project: ./chat-app/frontend
    host: appservice
    language: js
    docker:
      path: Dockerfile
      context: .
      image: ccsa-chat-frontend

  ecommerce-backend:
    project: ./ecommerce-app/backend
    host: appservice
    language: python
    docker:
      path: Dockerfile
      context: .
      image: ccsa-ecom-backend

  ecommerce-frontend:
    project: ./ecommerce-app/frontend
    host: appservice
    language: js
    docker:
      path: Dockerfile
      context: .
      image: ccsa-ecom-frontend
