# p = argparse.ArgumentParser()
# p.add_argument("--workspaceId", required=True)
# p.add_argument("--solutionname", required=True)
# p.add_argument("--backend_app_pid", required=True)
# p.add_argument("--backend_app_uid", required=True)
# p.add_argument("--exports-file", required=True)
# args = p.parse_args()
